name: Electron Forge Build

on:
  push:
    branches: [main, use-action]

jobs:
  build-linux:
    permissions:
      contents: write # to upload artifacts
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_BUILD_ENVIRONMENT: host
    steps:
      - uses: actions/checkout@v4
      - uses: canonical/setup-lxd@v0.1.2
      - run: |
          sudo snap install snapcraft --classic --channel=7.x
          echo "SNAPCRAFT_BUILD_ENVIRONMENT=lxd" >> $GITHUB_ENV
      - uses: holepunchto/make-pear-app@main
  # build-macos:
  #   permissions:
  #     contents: write # to upload artifacts
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: holepunchto/make-pear-app@main
  #       with:
  #         macos_certificate_base64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
  #         macos_p12_password: ${{ secrets.APPLE_P12_PASSWORD }}
  #         macos_provisioning_profile_base64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
  #         macos_keychain_password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
  #         macos_api_key_base64: ${{ secrets.APPLE_APIKEY }}
  #         macos_api_key_id: S3AG2UXSC5
  #         macos_api_key_issuer: 2067dae8-140d-4016-9a2b-d6ea80a20708
  #         macos_codesign_identity: ${{ secrets.MACOS_SIGNING_IDENTITY }}
  # build-win32:
  #   permissions:
  #     contents: write # to upload artifacts
  #   runs-on: self-hosted # self-hosted signer
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: holepunchto/make-pear-app@main
  #       with:
  #         windows_subject: ${{ secrets.WIN_SUBJECT }}
  #         windows_thumbprint: ${{ secrets.WIN_THUMBPRINT }}
